### PR TITLE
feat: user can create new categories.

### LINKED ISSUE #6: Create a Category
As an author I would like to be able to create a new category so that I can better classify my posts.

**Given** an author is on the Category list page  
**When** they select the `Create Category` button  
**Then** they should be directed to a form in which they can enter a new category name  

**Given** an author has entered a Category name  
**When** they click the `Save` button  
**Then** a new category should be saved to the database  
**And** the author should be directed to the Category list page

### PR DESCRIPTION
**Pull request by CheoR**
# Description

User can create new categories (through postman). 
Frontend portion sent as a separate pull request.

Closes #6 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

In terminal, run

`
watchgod request_handler.main 
`

In postman, under the `POST` tab,

`
http://localhost:8088/categories
`
in `body > raw`

```json
{
    "label": "new_label_here"
}
```

Successful creation returns the created object.

To view labels, in `SQL` file, run

```SQL
SELECT * FROM Categories;
```
# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by hrlnsnchz — APPROVED** [review]
Categories are posted to the db using postman. the GET request also works and reflects the newly added category.

**Review by Daniel-L-Ross — APPROVED** [review]
I was able to add a category from postman and view it with a SQL query.

**Review by hrlnsnchz — APPROVED** [review]
👍🏼

**Review by daprieu — APPROVED** [review]
you got my approval

**Comment by Daniel-L-Ross** [comment]
Looks good.

**Pull request merged**
